#!/usr/bin/env python3
import json
import sys
import subprocess
import os


if __name__ == "__main__":
    if len(sys.argv) == 1:
        print('Welcome!! You are in interactive mode\nThe following accounts are available ')
    
    elif len(sys.argv) == 2:
        acc_name = sys.argv[1]
        with open('data.json') as data_file:
            acc_list = json.load(data_file)
            for i in acc_list:
                if i['acc_name'] == acc_name:
                    subprocess.run(['git','config', '--global','user.name', acc_name])
                    subprocess.run(['git','config', '--global','user.email', i['email']])
                    try:
                        auth_sock = os.environ['SSH_AUTH_SOCK']
                        if auth_sock.find('agent') == -1:
                            subprocess.run(['eval', '$(ssh-agent -s)'])
                    except KeyError:                    
                            subprocess.run(['eval', '$(ssh-agent -s)'])
                    subprocess.run(['ssh-add', i['key_loc']])
                    with open('script.sh','w') as script:
                        script.write(f'#!/bin/bash\n\ngit config --global user.name {acc_name}\ngit config --global user.email {i['email']}\neval $(ssh-agent -s)\nssh-add {i['key_loc']}\n')
                        print(f"Account has been changed to {acc_name}")


    else:
        print("Error: Unknown No. of arguments given\nUsage: multigit [ACC_NAME]\nwhere[ACC_NAME] is optional.")